# Generated by Django 3.1.7 on 2021-03-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllAbberations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runid', models.CharField(default='', max_length=255)),
                ('sample', models.CharField(max_length=255)),
                ('genes', models.CharField(max_length=255)),
                ('variant_type', models.CharField(default='NA', max_length=255)),
                ('transcript', models.CharField(default='NA', max_length=255)),
                ('variants', models.CharField(default='NA', max_length=255)),
                ('length_bp', models.IntegerField(default='NA')),
                ('vaf', models.DecimalField(decimal_places=2, max_digits=4)),
                ('exon', models.IntegerField()),
                ('amino_acid_change', models.CharField(default='NA', max_length=255)),
                ('coverage', models.IntegerField()),
                ('tier', models.IntegerField()),
                ('locus', models.CharField(max_length=255)),
                ('interpretations', models.TextField(default='NA')),
                ('citations', models.TextField(default='NA')),
                ('variant_pmkb', models.TextField(default='NA')),
            ],
            options={
                'db_table': 'allabberations',
            },
        ),
        migrations.CreateModel(
            name='MyeloidInputReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runid', models.CharField(default='', max_length=255)),
                ('sample', models.CharField(max_length=255)),
                ('locus', models.CharField(max_length=255)),
                ('genes_myeloid', models.CharField(max_length=255)),
                ('variant_type', models.CharField(max_length=255)),
                ('exon', models.IntegerField()),
                ('transcript', models.CharField(max_length=255)),
                ('coding', models.CharField(max_length=255)),
                ('variant_effect', models.CharField(max_length=255)),
                ('length_bp', models.IntegerField()),
                ('vaf', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amino_acid_change', models.CharField(max_length=255)),
                ('coverage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PMKBdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=255)),
                ('tumor_type', models.TextField()),
                ('tissue_type', models.CharField(max_length=255)),
                ('variant', models.CharField(max_length=255)),
                ('tier', models.IntegerField()),
                ('interpretations', models.TextField()),
                ('citations', models.TextField()),
            ],
        ),
    ]
